apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: currencyservice

build:
  tagPolicy:
    sha256: { }
  local:
    push: true
  artifacts:
    - image: amsidhmicroservice/currencyconversion
      context: currency-conversion
      jib: {}
    - image: amsidhmicroservice/currencyexchange
      context: currency-exchange
      jib: {}

deploy:
  kubectl:
    manifests:
      - deployment/currency-service/currency-conversion/currencyconversion-*.yaml
      - deployment/currency-service/currency-exchange/currencyexchange-*.yaml
