apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: currencyservice
build:
  artifacts:
    - image: amsidhmicroservice/currencyconversion
      context: currency-conversion
      docker: { }
    - image: amsidhmicroservice/currencyexchange
      context: currency-exchange
      docker: { }
deploy:
  kubectl:
    manifests:
      - deployment/currency-service/currency-conversion/currencyconversion-*.yaml
      - deployment/currency-service/currency-exchange/currencyexchange-*.yaml
