#CurrencyExchange Service Configuration
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
    version: 1.1.3-RELEASE
  name: currency-exchange
spec:
  ports:
    - name: exchange-port
      port: 8181
  selector:
    app: currency-exchange
    version: 1.1.3-RELEASE
  sessionAffinity: ClientIP
  type: ClusterIP
