apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
    version: 1.1.0
  name: currency-exchange
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
        version: 1.1.0
    spec:
      containers:
        - image: amsidhmicroservice/kube-currency-exchange:1.1.0
          imagePullPolicy: Always
          name: currency-exchange
          ports:
            - name: tcp-exchange
              containerPort: 8181
          env:
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
