---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.16.3
        ports:
        - containerPort: 5601
          name: webinterface
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-client:9200"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-elastic
              key: password
        - name: XPACK_SECURITY_SESSION_IDLETIMEOUT
          value: "1d"
        - name: XPACK_SECURITY_SESSION_LIFESPAN
          value: "30d"
        - name: XPACK_SECURITY_ENCRYPTIONKEY
          value: "bbfe8ae38274521f9311cb5467cbee41"
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "abf6f2da5ba45222b4e66e38d50e7d63"
        - name: MONITORING_ENABLED
          value: "true"
        - name: XPACK_MONITORING_COLLECTION_ENABLED
          value: "true"
        - name: TZ
          value: "Asia/Kolkata"
        - name: I18N_LOCALE
          value: "as-IN"

        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-config
---