---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601   # external port where other service can communicate
    name: webinterface
    targetPort: 5601 # internal port on which current service is running
  selector:
    app: kibana
---