#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |-
    ################################################################
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>
    
    <source>
      @type tail
      path /var/log/containers/currency-conversion-*.log,/var/log/containers/currency-exchange-*.log,/var/log/containers/counter_default_count-*.log
      pos_file /var/log/fluentd-containers-currency.log.pos
      exclude_path ["/var/log/containers/fluent*", "/var/log/containers/monitoring*", "/var/log/containers/elastic*", "/var/log/containers/kibana*", "/var/log/containers/istio-*", "/var/log/containers/kube-*", "/var/log/containers/gke-*", "/var/log/containers/metrics*", "/var/log/containers/prometheus*", "/var/log/containers/pdcsi*", "/var/log/containers/konnectivity*", "/var/log/containers/kiali-*", "/var/log/containers/fluentbit-*", "/var/log/containers/fluentd-*", "/var/log/containers/*_istio-*", "/var/log/containers/l7-default-backend-*"]
      tag kubernetes.*
      refresh_interval 30
      read_from_head true
      emit_unmatched_lines true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key logTime
          time_format %Y-%m-%dT%H:%M:%S.%N%z
          keep_time_key true
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>
    
    <filter kubernetes.**>
      @type parser # record_transformer
      # @log_level debug
      <parse>
        @type json
      </parse>
      key_name log
    </filter>
    
    <filter kubernetes.**>
      @type kubernetes_metadata
      verify_ssl false
    </filter>
    
    <match kubernetes.**>
      @type elasticsearch_dynamic
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      suppress_type_name true
      logstash_format true
      logstash_prefix ${record['kubernetes']['container_name']}
      buffer_chunk_limit 2M
      reload_connections true
      reconnect_on_error true
      max_retry_wait 30
      disable_retry_limit
    </match>
    <match **>
      @type elasticsearch
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      suppress_type_name true
      logstash_format true
      # Set the chunk limits.
      buffer_chunk_limit 2M
      buffer_queue_limit 8
      # Never wait longer than 5 minutes between retries.
      max_retry_wait 30
      # Disable the limit on the number of retries (retry forever).
      disable_retry_limit
      # Use multiple threads for processing.
      num_threads 5
      reload_connections true
      reconnect_on_error true
    </match>