#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |-
    ################################################################
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
    <label @FLUENT_LOG>
      <match fluent.**>
        @type stdout
      </match>
    </label>
    
    <source>
      @type forward
      port 8181
      bind 0.0.0.0
      tag  raw.kubernetes.*
      chunk_size_warn_limit 2MB
      skip_invalid_event true 
    </source>
    
    
    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>
    
    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>
    
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
      verify_ssl false
    </filter>
    
    
    #exclude kube-system
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>
    
    <match **>
      @id elasticsearch_dynamic
      @type elasticsearch_dynamic
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      suppress_type_name true
      logstash_format true
      logstash_prefix ms-${record['kubernetes']['container_name']}
      request_timeout 30s
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
