apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - image: amsidhmicroservice/currencyconversion:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: currency-conversion
          ports:
            - name: liveness-port
              containerPort: 8282

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi

          readinessProbe:
            httpGet:
              path: /currency-conversion/
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60

          livenessProbe:
            httpGet:
              path: /currency-conversion/
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
spec:
  ports:
    - name: http
      port: 8282
  selector:
    app: currency-conversion
