apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currencyexchange
  name: currencyexchange
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currencyexchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currencyexchange
    spec:
      containers:
        - image: amsidhmicroservice/currencyexchange:latest
          imagePullPolicy: IfNotPresent
          name: currencyexchange
          ports:
            - name: liveness-port
              containerPort: 8181
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyexchange
  name: currencyexchange
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: "8181"
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: currencyexchange
  sessionAffinity: None
