apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
    version: 0.0.1-SNAPSHOT
  name: currency-conversion-v1
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
      version: 0.0.1-SNAPSHOT
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/currencyconversion:0.0.1-SNAPSHOT
          #        - image: gcr.io/microservice-324508/currencyconversion:latest
          imagePullPolicy: IfNotPresent
          name: currency-conversion
          ports:
            - name: liveness-port
              containerPort: 8282
          #          env:
          #            - name: CURRENCY_EXCHANGE_URI
          #              value: currency-exchange
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion-service
    version: 0.0.2-SNAPSHOT
  name: currency-conversion-service
spec:
  ports:
    - name: http
      port: 8282
  selector:
    app: currency-conversion-v1

