apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currencyconversion
  name: currencyconversion
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currencyconversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currencyconversion
    spec:
      containers:
        - image: amsidhmicroservice/currencyconversion:latest
#        - image: gcr.io/microservice-324508/currencyconversion:latest
          imagePullPolicy: IfNotPresent
          name: currencyconversion
          ports:
            - name: liveness-port
              containerPort: 8282
          env:
            - name: CURRENCY_EXCHANGE_URI
              value: currencyexchange
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyconversion
  name: currencyconversion
spec:
  type: LoadBalancer
  ports:
    - name: "8282"
      port: 8282
      targetPort: 8282
      protocol: TCP
  selector:
    app: currencyconversion
  sessionAffinity: None

