apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
    version: 1.1.0
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
        version: 1.1.0
    spec:
      containers:
        - image: amsidhmicroservice/kube-currency-conversion:1.1.0
          imagePullPolicy: Always
          name: currency-conversion
          ports:
            - name: tcp-conversion
              containerPort: 8282
          env:
            - name: CURRENCY_EXCHANGE_URL
              value: http://currency-exchange:8181
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
