apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
    version: 1.1.6-RELEASE
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
        version: 1.1.6-RELEASE
    spec:
      containers:
        - image: amsidhmicroservice/currency-conversion:1.1.6-RELEASE
          imagePullPolicy: IfNotPresent
          name: currency-conversion
          ports:
            - name: conversionport
              containerPort: 8282
          env:
            - name: CURRENCY_EXCHANGE_URL
              value: http://currency-exchange:8181
            - name: TZ
              value: "Asia/Kolkata"
            - name: I18N_LOCALE
              value: "as-IN"

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
