server:
  port: 8181

spring:
  profiles:
    include:
      - common
---
spring:
  application:
    name: currency-exchange

  #H2 Database configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:currency_exchange;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS currency_exchange
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      - hibernate.format_sql: true
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath*:schema/exchange-schema.sql
      data-locations: classpath*:data/exchange-data.sql
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
