apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
    version: 1.1.2
  name: currency-exchange
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: currency-exchange
        version: 1.1.2
    spec:
      containers:
        - image: amsidhmicroservice/kube-currency-exchange:1.1.2
          imagePullPolicy: Always
          name: currency-exchange
          ports:
            - name: tcp-exchange
              containerPort: 8181
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
