apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: infra
data:
  fluent.conf: |-
    ################################################################
    <system>
    root_dir /tmp/fluentd-buffers/
    </system>
    <label @FLUENT_LOG>
    <match fluent.**>
    @type stdout
    </match>
    </label>
    <source>
      @id source-currency-id
      @type tail
      path /var/log/containers/counter*.log, /var/log/containers/currency*.log
      pos_file /var/log/currency.log.pos
      exclude_path ["/var/log/containers/fluent*", "/var/log/containers/monitoring*", "/var/log/containers/elastic*", "/var/log/containers/kibana*", "/var/log/containers/istio-*", "/var/log/containers/kube-*", "/var/log/containers/gke-*", "/var/log/containers/metrics*", "/var/log/containers/prometheus*", "/var/log/containers/pdcsi*", "/var/log/containers/konnectivity*", "/var/log/containers/kiali-*", "/var/log/containers/fluentbit-*", "/var/log/containers/fluentd-*", "/var/log/containers/*_istio-*", "/var/log/containers/l7-default-backend-*"]
      tag  raw.kubernetes.*
      read_from_head true
      refresh_interval 5s
      encoding UTF-8
      <parse>
        @type multi_format
        <pattern>
          format json
          time_format %Y-%m-%dT%H:%M:%S.%NZ
          time_type string
          keep_time_key false
        </pattern>
        <pattern>
          format regexp
          expression /^(?<@timestamp>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
          keep_time_key false
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>
    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id detect_exceptions_id
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>
    
    <filter **>
      @id filter_kubernetes_metadata_id
      @type kubernetes_metadata
      allow_orphans false
      skip_labels true
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>  
    <match **>
      @id multi_target
      @type copy
      <store>
        @id ms-elastic-store
        @type elasticsearch_dynamic
        @log_level debug
        include_tag_key true
        time_key_exclude_timestamp false
        scheme http
        host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'localhost'}"
        port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
        user "#{ENV['FLUENT_ELASTICSEARCH_USER'] || 'elastic'}"
        password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD'] || 'xBqJXNkNm0CXSlakamdF'}"
        ssl_version TLSv1_2
        ssl_verify true
        suppress_type_name true
        logstash_format true
        logstash_prefix ms-${record['kubernetes']['container_name']}
        logstash_dateformat %Y.%m.%d
        type_name fluentd
        reconnect_on_error true
        reload_on_failure false
        reload_connections false
        slow_flush_log_threshold 25.0
        <buffer tag>
          @type file
          path /var/log/fluentd-buffers/ms-currency-service
          total_limit_size 1024MB
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 20
          flush_interval 5s
          retry_timeout 1m
          retry_max_interval 30
          chunk_limit_size 10M
          queue_limit_length 8
          overflow_action drop_oldest_chunk
          timekey 0.1h
        </buffer>
      </store>
      <store>
        @id copyToFile
        @type file
        path  /var/log/copy-log
        compress gzip
        <format>
          localtime false
        </format>
        <buffer time>
          timekey_wait 10m
          timekey 86400
          timekey_use_utc true
          path  /var/log/copy-log
        </buffer>
        <inject>
          localtime false
        </inject>
      </store>
    </match>

