imageName: amsidhmicroservice/currencyconversion:0.0.3-helm-SNAPSHOT
port: 8282
name: currency-conversion
healthCheck: /currency-conversion/
serviceType: LoadBalancer


version: 0.0.3-helm-SNAPSHOT
minReadySeconds: 45
resourceRequestMemory: 512Mi
resourceLimitsMemory: 1024Mi
restartPolicy: Always
terminationGracePeriodSeconds: 30
numberOfReplicas: 2

