# CurrencyConversion-Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
    version: 0.0.1-logsinjson-SNAPSHOT
  name: currency-conversion
spec:
  ports:
    - name: http
      port: 8282
  selector:
    app: currency-conversion
    version: 0.0.1-logsinjson-SNAPSHOT