# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 2-elastic-kibana-workflow

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy_ek_on_gke_job:
    name: deploy_ek_on_gke_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v2
      - name: Setup gcloud CLI and login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Access GKE Cluster
        run: |-
          echo "Display GCP account details"
          gcloud info
          echo "Installing gke-gcloud-auth-plugin"
          gcloud components install gke-gcloud-auth-plugin
          echo "Access to GKE Cluster"
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      - name: Deployment ElasticSearch And Kibana to the GKE Cluster
        run: |-
          echo "Delete exiting ElasticSearch And Kibana deployment"
          kubectl delete namespace elastic-kibana --ignore-not-found=true --grace-period=10

          echo "Deploy ElasticSearch And Kibana on GKE cluster"
          kubectl apply -f deployment/efk/elasticsearch-kibana/1-elastic-kibana-namespace.yaml,deployment/efk/elasticsearch-kibana/2-elastic-demo.yaml,deployment/efk/elasticsearch-kibana/3-kibana-demo.yaml
          kubectl get all -n elastic-kibana
