name: Istio Setup Setup on GKE Cluster
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Run this workflow if you are really looking to install Istio'
        required: true
        default: 'This workflow install Istio'
      home:
        description: 'Pune'
        required: false
        default: 'Maharashtra'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

      # Install gcloud on this Git Ubuntu temporary server
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info

      # Login to GKE Cluster
      - name: Login to GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      # Deployment to the EFK on GKE Cluster
      - name: Deployment to the EFK on GKE Cluster
        run: |-
          echo "Delete ISTIO Setup"
          kubectl delete namespace istio-system --ignore-not-found=true --grace-period=10

          echo "Setup ISTIO on GKE cluster"
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.6.8 TARGET_ARCH=x86_64 sh -
          cd istio-1.6.8
          export PATH=$PWD/bin:$PATH
          istioctl install --set profile=demo -y
          kubectl label namespace default istio-injection=enabled --overwrite=true
          kubectl get all -n istio-system

