# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 4-istio-workflow

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy_istio_job:
    name: deploy_istio_job
    runs-on: ubuntu-latest
    needs: [   build_clean_install_push_job ]
    steps:
      - name: Setup gcloud CLI and login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Display GCP information
        run: |-
          echo "Display GCP account details"
          gcloud info
          echo "Installing gke-gcloud-auth-plugin"
          gcloud components install gke-gcloud-auth-plugin
          echo "Access to GKE Cluster"
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"
      - name: Delete istio-system namespace from GKE Cluster
        run: |-
          echo "Delete ISTIO Setup"
          kubectl delete namespace istio-system --ignore-not-found=true --grace-period=1200
      - name: Setting up istio mesh on GKE Cluster
        run: |-
          echo "Setup ISTIO on GKE cluster"
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.14.3 TARGET_ARCH=x86_64 sh -
          cd istio-1.14.3
          export PATH=$PWD/bin:$PATH
          istioctl install --set profile=demo -y
          echo "Installing Istio demo profile successfully"
      - name: Enable istio-injection to default namespace
        run: |-
          echo "Enabling Istio-Injection on default namespace"
          kubectl label namespace default istio-injection=enabled --overwrite=true
          kubectl get all -n istio-system
      - name: Install Istio sample addon
        run: |-
          echo "Installing Istio sample addon"
          cd istio-1.14.3
          ls -al
          kubectl apply -f samples/addons
      
          

