# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 5-currency-service-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #schedule:
  # * is a special character in YAML, so you have to quote this string
  # Runs at 17:30 UTC every day.
  #- cron: '30 17 * * *'
  # Run on every 5 minutes
  #- cron: '0 0 * * 0'
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy_currency_service_job:
    name: deploy_currency_service_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v2
      - name: Setup gcloud CLI and login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Display GCP information
        run: |-
          echo "Display GCP account details"
          gcloud info
          echo "Installing gke-gcloud-auth-plugin"
          gcloud components install gke-gcloud-auth-plugin
          echo "Access to GKE Cluster"
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      - name: Delete existing Currency-Service if present on GKE Cluster
        run: |-
          echo "Delete Currency-Service Setup"
          kubectl delete -f deployment/currency-service/currency-conversion,deployment/currency-service/currency-exchange,deployment/efk/fluentd/5-counter.yaml --ignore-not-found=true --grace-period=10

          echo "Delete Gateway"
          kubectl delete -f deployment/gateway/istio --ignore-not-found=true --grace-period=10

      - name: Deploy Currency-Service on GKE Cluster
        run: |-
          kubectl get namespaces
          kubectl apply -f deployment/currency-service/currency-exchange,deployment/currency-service/currency-conversion,deployment/efk/fluentd/5-counter.yaml
          kubectl get services -o wide

          echo "Install Istio Gateway"
          kubectl apply -f deployment/gateway/istio
          kubectl get gateway -o wide
