name: Elastic-Kibana Setup on GKE Cluster
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log Level"
        required: true
        default: "warning"
    tags:
      description: "workflow manually trigger"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install gcloud on this Git Ubuntu temporary server
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info

      # Login to GKE Cluster
      - name: Login to GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      # Deployment to the EFK on GKE Cluster
      - name: Deployment to the EFK on GKE Cluster
        run: |-
          echo "Delete exiting EFK setup"
          kubectl delete namespace elastic-kibana --ignore-not-found=true --grace-period=10

          echo "Setup EFK on GKE cluster"
          kubectl apply -f deployment/efk/elasticsearch-kibana/1-elastic-kibana-namespace.yaml,deployment/efk/elasticsearch-kibana/2-elastic-demo.yaml,deployment/efk/elasticsearch-kibana/3-kibana-demo.yaml
          kubectl get all -n elastic-kibana

