# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: currencyservice-github-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # Runs at 17:30 UTC every day.Action schedules run at most every 5 minutes.
    #- cron: '30 17 * * *'
    # Runs at 00:00 UTC on Sun. Action schedules run at most every 5 minutes
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  deploy_istio:
    name: deploy_istio
    runs-on: ubuntu-latest
    steps:
      - name: Setup gcloud CLI and login to GCP
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Display GCP information
        run: |-
          gcloud info
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" --zone "$GKE_ZONE"

      - name: Deployment of the Istio Mesh to GKE Cluster
        run: |-
          echo "Delete Istio namespace"
          kubectl delete namespace istio-system --force --grace-period=0 --ignore-not-found=true

          echo "Setup Istio on GKE cluster"
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.14.1 TARGET_ARCH=x86_64 sh -
          cd istio-1.14.1
    
          echo "Setting Istio in classpath"
          export PATH=$PWD/bin:$PATH
    
          echo "Install istio demo profile "
          istioctl install --set profile=demo -y
    
          echo "Setting sidecar for default namespace"
          kubectl label namespace default istio-injection=enabled --overwrite=true
    
          echo "Get all resources from istion-system namespace"
          kubectl get all -n istio-system
  
