# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: currencyservice-github-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 4,17 * * *'
env:
  GCLOUD_PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}   # TODO: update to cluster name
  GKE_ZONE: ${{ secrets.GKE_ZONE }}       # TODO: update to cluster zone
  #DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}  # TODO: update deployment name if changed in deployment.yaml
  #GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Log in to Docker Hub with username and password configured in github secret
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.$DOCKER_PASSWORD }}

#      - name: Maven Clean, Install, Docker Build, Push and SonarCloud
#        run: mvn -B clean install -P build-push,sonar --file pom.xml

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: "$GKE_SA_KEY"
          project_id: "$GCLOUD_PROJECT_ID"

      # Get the GKE credentials so we can deploy to the cluster
      - name: Get the GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Deploy Currency Service images to the GKE cluster
      - name: Deployment to the GKE Cluster
        run: |-
          kubectl apply -f deployment/currencyconversion-deployment.yaml,deployment/currencyexchange-deployment.yaml
          kubectl get services -o wide

