# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan


on: pull_request

jobs:
     
  pipeline-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1       
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: Run Pipeline Scanner and reformat json
        continue-on-error: true
        run: java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_API_ID }}" -vkey "${{ secrets.VERACODE_API_KEY }}" --file "currency-conversion/target/currency-conversion-0.0.3-SNAPSHOT.jar" --project_name="currency-conversion" --fail_on_severity="Very High, High" --verbose -jf results.json
      - name: set execution
        if: ${{ always() }}
        run: chmod +x .github/files/json.sh .github/files/jq-linux64
      - name: copy resulst file
        if: ${{ always() }}
        run: cp /home/runner/work/verademo_java/verademo_java/results.json .github/files/
      - name: reformat json
        if: ${{ always() }}
        run: .github/files/json.sh
      - name: copy new json file
        if: ${{ always() }}
        run: cp veracode-sarif.json .github/files/       
      - name: show json file
        if: ${{ always() }}
        run: cat .github/files/veracode-sarif.json
      - uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          token: ${{ github.token }}
          sarif_file: .github/files/veracode-sarif.json
